// Code generated by cmd/genactions; DO NOT EDIT.
package actions

import (
	"github.com/idursun/jjui/internal/ui/actionargs"
	keybindings "github.com/idursun/jjui/internal/ui/bindings"
	"github.com/idursun/jjui/internal/ui/intents"
)

const (
	OwnerBookmarks           = "bookmarks"
	OwnerChoose              = "choose"
	OwnerCommandHistory      = "command_history"
	OwnerDiff                = "diff"
	OwnerFileSearch          = "file_search"
	OwnerGit                 = "git"
	OwnerHelp                = "help"
	OwnerInput               = "input"
	OwnerOplog               = "oplog"
	OwnerOplogQuickSearch    = "oplog.quick_search"
	OwnerPassword            = "password"
	OwnerRedo                = "redo"
	OwnerRevisions           = "revisions"
	OwnerAbandon             = "revisions.abandon"
	OwnerAceJump             = "revisions.ace_jump"
	OwnerDetails             = "revisions.details"
	OwnerDetailsConfirmation = "revisions.details.confirmation"
	OwnerDuplicate           = "revisions.duplicate"
	OwnerEvolog              = "revisions.evolog"
	OwnerInlineDescribe      = "revisions.inline_describe"
	OwnerQuickSearchInput    = "revisions.quick_search.input"
	OwnerRebase              = "revisions.rebase"
	OwnerRevert              = "revisions.revert"
	OwnerSetBookmark         = "revisions.set_bookmark"
	OwnerSetParents          = "revisions.set_parents"
	OwnerSquash              = "revisions.squash"
	OwnerTargetPicker        = "revisions.target_picker"
	OwnerRevset              = "revset"
	OwnerStatusInput         = "status.input"
	OwnerUi                  = "ui"
	OwnerUiPreview           = "ui.preview"
	OwnerUndo                = "undo"

	BookmarksApply                         keybindings.Action = "bookmarks.apply"
	BookmarksBookmarkDelete                keybindings.Action = "bookmarks.bookmark_delete"
	BookmarksBookmarkForget                keybindings.Action = "bookmarks.bookmark_forget"
	BookmarksBookmarkMove                  keybindings.Action = "bookmarks.bookmark_move"
	BookmarksBookmarkTrack                 keybindings.Action = "bookmarks.bookmark_track"
	BookmarksBookmarkUntrack               keybindings.Action = "bookmarks.bookmark_untrack"
	BookmarksCancel                        keybindings.Action = "bookmarks.cancel"
	BookmarksCycleRemotes                  keybindings.Action = "bookmarks.cycle_remotes"
	BookmarksCycleRemotesBack              keybindings.Action = "bookmarks.cycle_remotes_back"
	BookmarksFilter                        keybindings.Action = "bookmarks.filter"
	BookmarksMoveDown                      keybindings.Action = "bookmarks.move_down"
	BookmarksMoveUp                        keybindings.Action = "bookmarks.move_up"
	BookmarksPageDown                      keybindings.Action = "bookmarks.page_down"
	BookmarksPageUp                        keybindings.Action = "bookmarks.page_up"
	BookmarksQuit                          keybindings.Action = "bookmarks.quit"
	ChooseApply                            keybindings.Action = "choose.apply"
	ChooseCancel                           keybindings.Action = "choose.cancel"
	ChooseMoveDown                         keybindings.Action = "choose.move_down"
	ChooseMoveUp                           keybindings.Action = "choose.move_up"
	CommandHistoryClose                    keybindings.Action = "command_history.close"
	CommandHistoryDeleteSelected           keybindings.Action = "command_history.delete_selected"
	CommandHistoryMoveDown                 keybindings.Action = "command_history.move_down"
	CommandHistoryMoveUp                   keybindings.Action = "command_history.move_up"
	DiffHalfPageDown                       keybindings.Action = "diff.half_page_down"
	DiffHalfPageUp                         keybindings.Action = "diff.half_page_up"
	DiffLeft                               keybindings.Action = "diff.left"
	DiffMoveBottom                         keybindings.Action = "diff.move_bottom"
	DiffMoveTop                            keybindings.Action = "diff.move_top"
	DiffPageDown                           keybindings.Action = "diff.page_down"
	DiffPageUp                             keybindings.Action = "diff.page_up"
	DiffRight                              keybindings.Action = "diff.right"
	DiffScrollDown                         keybindings.Action = "diff.scroll_down"
	DiffScrollUp                           keybindings.Action = "diff.scroll_up"
	DiffShow                               keybindings.Action = "diff.show"
	DiffToggleWrap                         keybindings.Action = "diff.toggle_wrap"
	FileSearchApply                        keybindings.Action = "file_search.apply"
	FileSearchCancel                       keybindings.Action = "file_search.cancel"
	FileSearchEdit                         keybindings.Action = "file_search.edit"
	FileSearchMoveDown                     keybindings.Action = "file_search.move_down"
	FileSearchMoveUp                       keybindings.Action = "file_search.move_up"
	FileSearchPageDown                     keybindings.Action = "file_search.page_down"
	FileSearchPageUp                       keybindings.Action = "file_search.page_up"
	FileSearchPreviewHalfPageDown          keybindings.Action = "file_search.preview_half_page_down"
	FileSearchPreviewHalfPageUp            keybindings.Action = "file_search.preview_half_page_up"
	FileSearchToggle                       keybindings.Action = "file_search.toggle"
	GitApply                               keybindings.Action = "git.apply"
	GitCancel                              keybindings.Action = "git.cancel"
	GitCycleRemotes                        keybindings.Action = "git.cycle_remotes"
	GitCycleRemotesBack                    keybindings.Action = "git.cycle_remotes_back"
	GitFetch                               keybindings.Action = "git.fetch"
	GitFilter                              keybindings.Action = "git.filter"
	GitMoveDown                            keybindings.Action = "git.move_down"
	GitMoveUp                              keybindings.Action = "git.move_up"
	GitPageDown                            keybindings.Action = "git.page_down"
	GitPageUp                              keybindings.Action = "git.page_up"
	GitPush                                keybindings.Action = "git.push"
	GitQuit                                keybindings.Action = "git.quit"
	HelpApply                              keybindings.Action = "help.apply"
	HelpCancel                             keybindings.Action = "help.cancel"
	HelpClose                              keybindings.Action = "help.close"
	HelpFilter                             keybindings.Action = "help.filter"
	HelpMoveBottom                         keybindings.Action = "help.move_bottom"
	HelpMoveTop                            keybindings.Action = "help.move_top"
	HelpPageDown                           keybindings.Action = "help.page_down"
	HelpPageUp                             keybindings.Action = "help.page_up"
	HelpScrollDown                         keybindings.Action = "help.scroll_down"
	HelpScrollUp                           keybindings.Action = "help.scroll_up"
	InputApply                             keybindings.Action = "input.apply"
	InputCancel                            keybindings.Action = "input.cancel"
	OplogClose                             keybindings.Action = "oplog.close"
	OplogDiff                              keybindings.Action = "oplog.diff"
	OplogMoveDown                          keybindings.Action = "oplog.move_down"
	OplogMoveUp                            keybindings.Action = "oplog.move_up"
	OplogPageDown                          keybindings.Action = "oplog.page_down"
	OplogPageUp                            keybindings.Action = "oplog.page_up"
	OplogQuickSearchQuickSearchClear       keybindings.Action = "oplog.quick_search.quick_search_clear"
	OplogQuickSearchQuickSearchNext        keybindings.Action = "oplog.quick_search.quick_search_next"
	OplogQuickSearchQuickSearchPrev        keybindings.Action = "oplog.quick_search.quick_search_prev"
	OplogQuit                              keybindings.Action = "oplog.quit"
	OplogRestore                           keybindings.Action = "oplog.restore"
	OplogRevert                            keybindings.Action = "oplog.revert"
	PasswordApply                          keybindings.Action = "password.apply"
	PasswordCancel                         keybindings.Action = "password.cancel"
	RedoApply                              keybindings.Action = "redo.apply"
	RedoCancel                             keybindings.Action = "redo.cancel"
	RedoNext                               keybindings.Action = "redo.next"
	RedoPrev                               keybindings.Action = "redo.prev"
	RevisionsAbandonAceJump                keybindings.Action = "revisions.abandon.ace_jump"
	RevisionsAbandonApply                  keybindings.Action = "revisions.abandon.apply"
	RevisionsAbandonCancel                 keybindings.Action = "revisions.abandon.cancel"
	RevisionsAbandonForceApply             keybindings.Action = "revisions.abandon.force_apply"
	RevisionsAbandonJumpToWorkingCopy      keybindings.Action = "revisions.abandon.jump_to_working_copy"
	RevisionsAbandonSelectDescendants      keybindings.Action = "revisions.abandon.select_descendants"
	RevisionsAbandonToggleSelect           keybindings.Action = "revisions.abandon.toggle_select"
	RevisionsAbsorb                        keybindings.Action = "revisions.absorb"
	RevisionsAceJump                       keybindings.Action = "revisions.ace_jump"
	RevisionsAceJumpApply                  keybindings.Action = "revisions.ace_jump.apply"
	RevisionsAceJumpCancel                 keybindings.Action = "revisions.ace_jump.cancel"
	RevisionsApply                         keybindings.Action = "revisions.apply"
	RevisionsCommit                        keybindings.Action = "revisions.commit"
	RevisionsDescribe                      keybindings.Action = "revisions.describe"
	RevisionsDetailsAbsorb                 keybindings.Action = "revisions.details.absorb"
	RevisionsDetailsCancel                 keybindings.Action = "revisions.details.cancel"
	RevisionsDetailsConfirmationApply      keybindings.Action = "revisions.details.confirmation.apply"
	RevisionsDetailsConfirmationCancel     keybindings.Action = "revisions.details.confirmation.cancel"
	RevisionsDetailsConfirmationForceApply keybindings.Action = "revisions.details.confirmation.force_apply"
	RevisionsDetailsConfirmationNext       keybindings.Action = "revisions.details.confirmation.next"
	RevisionsDetailsConfirmationPrev       keybindings.Action = "revisions.details.confirmation.prev"
	RevisionsDetailsDiff                   keybindings.Action = "revisions.details.diff"
	RevisionsDetailsMoveDown               keybindings.Action = "revisions.details.move_down"
	RevisionsDetailsMoveUp                 keybindings.Action = "revisions.details.move_up"
	RevisionsDetailsPageDown               keybindings.Action = "revisions.details.page_down"
	RevisionsDetailsPageUp                 keybindings.Action = "revisions.details.page_up"
	RevisionsDetailsQuit                   keybindings.Action = "revisions.details.quit"
	RevisionsDetailsRefresh                keybindings.Action = "revisions.details.refresh"
	RevisionsDetailsRestore                keybindings.Action = "revisions.details.restore"
	RevisionsDetailsRevisionsChangingFile  keybindings.Action = "revisions.details.revisions_changing_file"
	RevisionsDetailsSelectFile             keybindings.Action = "revisions.details.select_file"
	RevisionsDetailsSplit                  keybindings.Action = "revisions.details.split"
	RevisionsDetailsSplitParallel          keybindings.Action = "revisions.details.split_parallel"
	RevisionsDetailsSquash                 keybindings.Action = "revisions.details.squash"
	RevisionsDetailsToggleSelect           keybindings.Action = "revisions.details.toggle_select"
	RevisionsDiff                          keybindings.Action = "revisions.diff"
	RevisionsDiffEdit                      keybindings.Action = "revisions.diff_edit"
	RevisionsDuplicateAceJump              keybindings.Action = "revisions.duplicate.ace_jump"
	RevisionsDuplicateApply                keybindings.Action = "revisions.duplicate.apply"
	RevisionsDuplicateCancel               keybindings.Action = "revisions.duplicate.cancel"
	RevisionsDuplicateForceApply           keybindings.Action = "revisions.duplicate.force_apply"
	RevisionsDuplicateJumpToWorkingCopy    keybindings.Action = "revisions.duplicate.jump_to_working_copy"
	RevisionsDuplicateSetTarget            keybindings.Action = "revisions.duplicate.set_target"
	RevisionsDuplicateTargetPicker         keybindings.Action = "revisions.duplicate.target_picker"
	RevisionsEdit                          keybindings.Action = "revisions.edit"
	RevisionsEvologApply                   keybindings.Action = "revisions.evolog.apply"
	RevisionsEvologCancel                  keybindings.Action = "revisions.evolog.cancel"
	RevisionsEvologDiff                    keybindings.Action = "revisions.evolog.diff"
	RevisionsEvologMoveDown                keybindings.Action = "revisions.evolog.move_down"
	RevisionsEvologMoveUp                  keybindings.Action = "revisions.evolog.move_up"
	RevisionsEvologPageDown                keybindings.Action = "revisions.evolog.page_down"
	RevisionsEvologPageUp                  keybindings.Action = "revisions.evolog.page_up"
	RevisionsEvologQuit                    keybindings.Action = "revisions.evolog.quit"
	RevisionsEvologRestore                 keybindings.Action = "revisions.evolog.restore"
	RevisionsForceApply                    keybindings.Action = "revisions.force_apply"
	RevisionsForceEdit                     keybindings.Action = "revisions.force_edit"
	RevisionsInlineDescribeAccept          keybindings.Action = "revisions.inline_describe.accept"
	RevisionsInlineDescribeCancel          keybindings.Action = "revisions.inline_describe.cancel"
	RevisionsInlineDescribeEditor          keybindings.Action = "revisions.inline_describe.editor"
	RevisionsJumpToChildren                keybindings.Action = "revisions.jump_to_children"
	RevisionsJumpToParent                  keybindings.Action = "revisions.jump_to_parent"
	RevisionsJumpToWorkingCopy             keybindings.Action = "revisions.jump_to_working_copy"
	RevisionsMoveDown                      keybindings.Action = "revisions.move_down"
	RevisionsMoveUp                        keybindings.Action = "revisions.move_up"
	RevisionsNew                           keybindings.Action = "revisions.new"
	RevisionsOpenAbandon                   keybindings.Action = "revisions.open_abandon"
	RevisionsOpenDetails                   keybindings.Action = "revisions.open_details"
	RevisionsOpenDuplicate                 keybindings.Action = "revisions.open_duplicate"
	RevisionsOpenEvolog                    keybindings.Action = "revisions.open_evolog"
	RevisionsOpenInlineDescribe            keybindings.Action = "revisions.open_inline_describe"
	RevisionsOpenRebase                    keybindings.Action = "revisions.open_rebase"
	RevisionsOpenRevert                    keybindings.Action = "revisions.open_revert"
	RevisionsOpenSetBookmark               keybindings.Action = "revisions.open_set_bookmark"
	RevisionsOpenSetParents                keybindings.Action = "revisions.open_set_parents"
	RevisionsOpenSquash                    keybindings.Action = "revisions.open_squash"
	RevisionsPageDown                      keybindings.Action = "revisions.page_down"
	RevisionsPageUp                        keybindings.Action = "revisions.page_up"
	RevisionsQuickSearchInputApply         keybindings.Action = "revisions.quick_search.input.apply"
	RevisionsQuickSearchInputCancel        keybindings.Action = "revisions.quick_search.input.cancel"
	RevisionsQuickSearchClear              keybindings.Action = "revisions.quick_search_clear"
	RevisionsQuickSearchNext               keybindings.Action = "revisions.quick_search_next"
	RevisionsQuickSearchPrev               keybindings.Action = "revisions.quick_search_prev"
	RevisionsRebaseAceJump                 keybindings.Action = "revisions.rebase.ace_jump"
	RevisionsRebaseApply                   keybindings.Action = "revisions.rebase.apply"
	RevisionsRebaseCancel                  keybindings.Action = "revisions.rebase.cancel"
	RevisionsRebaseForceApply              keybindings.Action = "revisions.rebase.force_apply"
	RevisionsRebaseJumpToWorkingCopy       keybindings.Action = "revisions.rebase.jump_to_working_copy"
	RevisionsRebaseSetSource               keybindings.Action = "revisions.rebase.set_source"
	RevisionsRebaseSetTarget               keybindings.Action = "revisions.rebase.set_target"
	RevisionsRebaseSkipEmptied             keybindings.Action = "revisions.rebase.skip_emptied"
	RevisionsRebaseTargetPicker            keybindings.Action = "revisions.rebase.target_picker"
	RevisionsRefresh                       keybindings.Action = "revisions.refresh"
	RevisionsRevertApply                   keybindings.Action = "revisions.revert.apply"
	RevisionsRevertCancel                  keybindings.Action = "revisions.revert.cancel"
	RevisionsRevertForceApply              keybindings.Action = "revisions.revert.force_apply"
	RevisionsRevertSetTarget               keybindings.Action = "revisions.revert.set_target"
	RevisionsRevertTargetPicker            keybindings.Action = "revisions.revert.target_picker"
	RevisionsSetBookmarkApply              keybindings.Action = "revisions.set_bookmark.apply"
	RevisionsSetBookmarkAutocomplete       keybindings.Action = "revisions.set_bookmark.autocomplete"
	RevisionsSetBookmarkAutocompleteBack   keybindings.Action = "revisions.set_bookmark.autocomplete_back"
	RevisionsSetBookmarkCancel             keybindings.Action = "revisions.set_bookmark.cancel"
	RevisionsSetParentsAceJump             keybindings.Action = "revisions.set_parents.ace_jump"
	RevisionsSetParentsApply               keybindings.Action = "revisions.set_parents.apply"
	RevisionsSetParentsCancel              keybindings.Action = "revisions.set_parents.cancel"
	RevisionsSetParentsJumpToWorkingCopy   keybindings.Action = "revisions.set_parents.jump_to_working_copy"
	RevisionsSetParentsToggleSelect        keybindings.Action = "revisions.set_parents.toggle_select"
	RevisionsSplit                         keybindings.Action = "revisions.split"
	RevisionsSplitParallel                 keybindings.Action = "revisions.split_parallel"
	RevisionsSquashAceJump                 keybindings.Action = "revisions.squash.ace_jump"
	RevisionsSquashApply                   keybindings.Action = "revisions.squash.apply"
	RevisionsSquashCancel                  keybindings.Action = "revisions.squash.cancel"
	RevisionsSquashForceApply              keybindings.Action = "revisions.squash.force_apply"
	RevisionsSquashInteractive             keybindings.Action = "revisions.squash.interactive"
	RevisionsSquashJumpToWorkingCopy       keybindings.Action = "revisions.squash.jump_to_working_copy"
	RevisionsSquashKeepEmptied             keybindings.Action = "revisions.squash.keep_emptied"
	RevisionsSquashTargetPicker            keybindings.Action = "revisions.squash.target_picker"
	RevisionsSquashUseDestinationMsg       keybindings.Action = "revisions.squash.use_destination_msg"
	RevisionsTargetPickerApply             keybindings.Action = "revisions.target_picker.apply"
	RevisionsTargetPickerAutocomplete      keybindings.Action = "revisions.target_picker.autocomplete"
	RevisionsTargetPickerAutocompleteBack  keybindings.Action = "revisions.target_picker.autocomplete_back"
	RevisionsTargetPickerCancel            keybindings.Action = "revisions.target_picker.cancel"
	RevisionsTargetPickerForceApply        keybindings.Action = "revisions.target_picker.force_apply"
	RevisionsTargetPickerMoveDown          keybindings.Action = "revisions.target_picker.move_down"
	RevisionsTargetPickerMoveUp            keybindings.Action = "revisions.target_picker.move_up"
	RevisionsToggleSelect                  keybindings.Action = "revisions.toggle_select"
	RevsetApply                            keybindings.Action = "revset.apply"
	RevsetAutocomplete                     keybindings.Action = "revset.autocomplete"
	RevsetAutocompleteBack                 keybindings.Action = "revset.autocomplete_back"
	RevsetCancel                           keybindings.Action = "revset.cancel"
	RevsetEdit                             keybindings.Action = "revset.edit"
	RevsetMoveDown                         keybindings.Action = "revset.move_down"
	RevsetMoveUp                           keybindings.Action = "revset.move_up"
	RevsetReset                            keybindings.Action = "revset.reset"
	RevsetSet                              keybindings.Action = "revset.set"
	StatusInputApply                       keybindings.Action = "status.input.apply"
	StatusInputAutocomplete                keybindings.Action = "status.input.autocomplete"
	StatusInputCancel                      keybindings.Action = "status.input.cancel"
	StatusInputMoveDown                    keybindings.Action = "status.input.move_down"
	StatusInputMoveUp                      keybindings.Action = "status.input.move_up"
	StatusInputPageDown                    keybindings.Action = "status.input.page_down"
	StatusInputPageUp                      keybindings.Action = "status.input.page_up"
	UiCancel                               keybindings.Action = "ui.cancel"
	UiExecJj                               keybindings.Action = "ui.exec_jj"
	UiExecShell                            keybindings.Action = "ui.exec_shell"
	UiExpandStatus                         keybindings.Action = "ui.expand_status"
	UiFileSearchToggle                     keybindings.Action = "ui.file_search_toggle"
	UiOpenBookmarks                        keybindings.Action = "ui.open_bookmarks"
	UiOpenCommandHistory                   keybindings.Action = "ui.open_command_history"
	UiOpenGit                              keybindings.Action = "ui.open_git"
	UiOpenHelp                             keybindings.Action = "ui.open_help"
	UiOpenOplog                            keybindings.Action = "ui.open_oplog"
	UiOpenRedo                             keybindings.Action = "ui.open_redo"
	UiOpenRevset                           keybindings.Action = "ui.open_revset"
	UiOpenUndo                             keybindings.Action = "ui.open_undo"
	UiPreviewShow                          keybindings.Action = "ui.preview.show"
	UiPreviewExpand                        keybindings.Action = "ui.preview_expand"
	UiPreviewHalfPageDown                  keybindings.Action = "ui.preview_half_page_down"
	UiPreviewHalfPageUp                    keybindings.Action = "ui.preview_half_page_up"
	UiPreviewScrollDown                    keybindings.Action = "ui.preview_scroll_down"
	UiPreviewScrollUp                      keybindings.Action = "ui.preview_scroll_up"
	UiPreviewShrink                        keybindings.Action = "ui.preview_shrink"
	UiPreviewToggle                        keybindings.Action = "ui.preview_toggle"
	UiPreviewToggleBottom                  keybindings.Action = "ui.preview_toggle_bottom"
	UiQuickSearch                          keybindings.Action = "ui.quick_search"
	UiQuit                                 keybindings.Action = "ui.quit"
	UiSuspend                              keybindings.Action = "ui.suspend"
	UndoApply                              keybindings.Action = "undo.apply"
	UndoCancel                             keybindings.Action = "undo.cancel"
	UndoNext                               keybindings.Action = "undo.next"
	UndoPrev                               keybindings.Action = "undo.prev"
)

func IsRevisionsOwner(owner string) bool {
	switch owner {
	case OwnerCommandHistory, OwnerHelp, OwnerOplogQuickSearch, OwnerRevisions, OwnerAbandon, OwnerAceJump, OwnerDetails, OwnerDetailsConfirmation, OwnerDuplicate, OwnerEvolog, OwnerInlineDescribe, OwnerQuickSearchInput, OwnerRebase, OwnerRevert, OwnerSetBookmark, OwnerSetParents, OwnerSquash, OwnerTargetPicker:
		return true
	default:
		return false
	}
}

func ResolveIntent(owner string, action keybindings.Action, args map[string]any) (intents.Intent, bool) {
	switch owner {
	case OwnerBookmarks:
		switch action {
		case keybindings.Action("bookmarks.apply"):
			return intents.Apply{}, true
		case keybindings.Action("bookmarks.bookmark_delete"):
			return intents.BookmarksFilter{Kind: intents.BookmarksFilterDelete}, true
		case keybindings.Action("bookmarks.bookmark_forget"):
			return intents.BookmarksFilter{Kind: intents.BookmarksFilterForget}, true
		case keybindings.Action("bookmarks.bookmark_move"):
			return intents.BookmarksFilter{Kind: intents.BookmarksFilterMove}, true
		case keybindings.Action("bookmarks.bookmark_track"):
			return intents.BookmarksFilter{Kind: intents.BookmarksFilterTrack}, true
		case keybindings.Action("bookmarks.bookmark_untrack"):
			return intents.BookmarksFilter{Kind: intents.BookmarksFilterUntrack}, true
		case keybindings.Action("bookmarks.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("bookmarks.cycle_remotes"):
			return intents.BookmarksCycleRemotes{Delta: 1}, true
		case keybindings.Action("bookmarks.cycle_remotes_back"):
			return intents.BookmarksCycleRemotes{Delta: -1}, true
		case keybindings.Action("bookmarks.filter"):
			return intents.BookmarksOpenFilter{}, true
		case keybindings.Action("bookmarks.move_down"):
			return intents.BookmarksNavigate{Delta: 1}, true
		case keybindings.Action("bookmarks.move_up"):
			return intents.BookmarksNavigate{Delta: -1}, true
		case keybindings.Action("bookmarks.page_down"):
			return intents.BookmarksNavigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("bookmarks.page_up"):
			return intents.BookmarksNavigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("bookmarks.quit"):
			return intents.Quit{}, true
		}
	case OwnerChoose:
		switch action {
		case keybindings.Action("choose.apply"):
			return intents.ChooseApply{}, true
		case keybindings.Action("choose.cancel"):
			return intents.ChooseCancel{}, true
		case keybindings.Action("choose.move_down"):
			return intents.ChooseNavigate{Delta: 1}, true
		case keybindings.Action("choose.move_up"):
			return intents.ChooseNavigate{Delta: -1}, true
		}
	case OwnerCommandHistory:
		switch action {
		case keybindings.Action("command_history.close"):
			return intents.CommandHistoryClose{}, true
		case keybindings.Action("command_history.delete_selected"):
			return intents.CommandHistoryDeleteSelected{}, true
		case keybindings.Action("command_history.move_down"):
			return intents.CommandHistoryNavigate{Delta: 1}, true
		case keybindings.Action("command_history.move_up"):
			return intents.CommandHistoryNavigate{Delta: -1}, true
		}
	case OwnerDiff:
		switch action {
		case keybindings.Action("diff.half_page_down"):
			return intents.DiffScroll{Kind: intents.DiffHalfPageDown}, true
		case keybindings.Action("diff.half_page_up"):
			return intents.DiffScroll{Kind: intents.DiffHalfPageUp}, true
		case keybindings.Action("diff.left"):
			return intents.DiffScrollHorizontal{Kind: intents.DiffScrollLeft}, true
		case keybindings.Action("diff.move_bottom"):
			return intents.DiffScroll{Kind: intents.DiffMoveBottom}, true
		case keybindings.Action("diff.move_top"):
			return intents.DiffScroll{Kind: intents.DiffMoveTop}, true
		case keybindings.Action("diff.page_down"):
			return intents.DiffScroll{Kind: intents.DiffPageDown}, true
		case keybindings.Action("diff.page_up"):
			return intents.DiffScroll{Kind: intents.DiffPageUp}, true
		case keybindings.Action("diff.right"):
			return intents.DiffScrollHorizontal{Kind: intents.DiffScrollRight}, true
		case keybindings.Action("diff.scroll_down"):
			return intents.DiffScroll{Kind: intents.DiffScrollDown}, true
		case keybindings.Action("diff.scroll_up"):
			return intents.DiffScroll{Kind: intents.DiffScrollUp}, true
		case keybindings.Action("diff.show"):
			return intents.DiffShow{Content: actionargs.StringArg(args, "content", "")}, true
		case keybindings.Action("diff.toggle_wrap"):
			return intents.DiffToggleWrap{}, true
		}
	case OwnerFileSearch:
		switch action {
		case keybindings.Action("file_search.apply"):
			return intents.Apply{}, true
		case keybindings.Action("file_search.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("file_search.edit"):
			return intents.FileSearchEdit{}, true
		case keybindings.Action("file_search.move_down"):
			return intents.FileSearchNavigate{Delta: -1}, true
		case keybindings.Action("file_search.move_up"):
			return intents.FileSearchNavigate{Delta: 1}, true
		case keybindings.Action("file_search.page_down"):
			return intents.FileSearchPreviewScroll{Kind: intents.PreviewPageDown}, true
		case keybindings.Action("file_search.page_up"):
			return intents.FileSearchPreviewScroll{Kind: intents.PreviewPageUp}, true
		case keybindings.Action("file_search.preview_half_page_down"):
			return intents.FileSearchPreviewScroll{Kind: intents.PreviewHalfPageDown}, true
		case keybindings.Action("file_search.preview_half_page_up"):
			return intents.FileSearchPreviewScroll{Kind: intents.PreviewHalfPageUp}, true
		case keybindings.Action("file_search.toggle"):
			return intents.FileSearchTogglePreview{}, true
		}
	case OwnerGit:
		switch action {
		case keybindings.Action("git.apply"):
			return intents.Apply{}, true
		case keybindings.Action("git.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("git.cycle_remotes"):
			return intents.GitCycleRemotes{Delta: 1}, true
		case keybindings.Action("git.cycle_remotes_back"):
			return intents.GitCycleRemotes{Delta: -1}, true
		case keybindings.Action("git.fetch"):
			return intents.GitFilter{Kind: intents.GitFilterFetch}, true
		case keybindings.Action("git.filter"):
			return intents.GitOpenFilter{}, true
		case keybindings.Action("git.move_down"):
			return intents.GitNavigate{Delta: 1}, true
		case keybindings.Action("git.move_up"):
			return intents.GitNavigate{Delta: -1}, true
		case keybindings.Action("git.page_down"):
			return intents.GitNavigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("git.page_up"):
			return intents.GitNavigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("git.push"):
			return intents.GitFilter{Kind: intents.GitFilterPush}, true
		case keybindings.Action("git.quit"):
			return intents.Quit{}, true
		}
	case OwnerHelp:
		switch action {
		case keybindings.Action("help.apply"):
			return intents.Apply{}, true
		case keybindings.Action("help.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("help.close"):
			return intents.HelpClose{}, true
		case keybindings.Action("help.filter"):
			return intents.HelpFilter{}, true
		case keybindings.Action("help.move_bottom"):
			return intents.HelpScroll{Delta: 999999}, true
		case keybindings.Action("help.move_top"):
			return intents.HelpScroll{Delta: 0}, true
		case keybindings.Action("help.page_down"):
			return intents.HelpScroll{Delta: 10}, true
		case keybindings.Action("help.page_up"):
			return intents.HelpScroll{Delta: -10}, true
		case keybindings.Action("help.scroll_down"):
			return intents.HelpScroll{Delta: 1}, true
		case keybindings.Action("help.scroll_up"):
			return intents.HelpScroll{Delta: -1}, true
		}
	case OwnerInput:
		switch action {
		case keybindings.Action("input.apply"):
			return intents.Apply{}, true
		case keybindings.Action("input.cancel"):
			return intents.Cancel{}, true
		}
	case OwnerOplog:
		switch action {
		case keybindings.Action("oplog.close"):
			return intents.OpLogClose{}, true
		case keybindings.Action("oplog.diff"):
			return intents.OpLogShowDiff{}, true
		case keybindings.Action("oplog.move_down"):
			return intents.OpLogNavigate{Delta: 1}, true
		case keybindings.Action("oplog.move_up"):
			return intents.OpLogNavigate{Delta: -1}, true
		case keybindings.Action("oplog.page_down"):
			return intents.OpLogNavigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("oplog.page_up"):
			return intents.OpLogNavigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("oplog.quit"):
			return intents.Quit{}, true
		case keybindings.Action("oplog.restore"):
			return intents.OpLogRestore{}, true
		case keybindings.Action("oplog.revert"):
			return intents.OpLogRevert{}, true
		}
	case OwnerOplogQuickSearch:
		switch action {
		case keybindings.Action("oplog.quick_search.quick_search_clear"):
			return intents.OpLogQuickSearchClear{}, true
		case keybindings.Action("oplog.quick_search.quick_search_next"):
			return intents.QuickSearchCycle{}, true
		case keybindings.Action("oplog.quick_search.quick_search_prev"):
			return intents.QuickSearchCycle{Reverse: true}, true
		}
	case OwnerPassword:
		switch action {
		case keybindings.Action("password.apply"):
			return intents.Apply{}, true
		case keybindings.Action("password.cancel"):
			return intents.Cancel{}, true
		}
	case OwnerRedo:
		switch action {
		case keybindings.Action("redo.apply"):
			return intents.Apply{}, true
		case keybindings.Action("redo.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("redo.next"):
			return intents.OptionSelect{Delta: 1}, true
		case keybindings.Action("redo.prev"):
			return intents.OptionSelect{Delta: -1}, true
		}
	case OwnerRevisions:
		switch action {
		case keybindings.Action("revisions.absorb"):
			return intents.Absorb{}, true
		case keybindings.Action("revisions.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.commit"):
			return intents.CommitWorkingCopy{}, true
		case keybindings.Action("revisions.describe"):
			return intents.Describe{}, true
		case keybindings.Action("revisions.diff"):
			return intents.ShowDiff{}, true
		case keybindings.Action("revisions.diff_edit"):
			return intents.DiffEdit{}, true
		case keybindings.Action("revisions.edit"):
			return intents.StartEdit{}, true
		case keybindings.Action("revisions.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.force_edit"):
			return intents.StartEdit{IgnoreImmutable: true}, true
		case keybindings.Action("revisions.jump_to_children"):
			return intents.Navigate{Target: intents.TargetChild}, true
		case keybindings.Action("revisions.jump_to_parent"):
			return intents.Navigate{Target: intents.TargetParent}, true
		case keybindings.Action("revisions.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.move_down"):
			return intents.Navigate{Delta: 1}, true
		case keybindings.Action("revisions.move_up"):
			return intents.Navigate{Delta: -1}, true
		case keybindings.Action("revisions.new"):
			return intents.StartNew{}, true
		case keybindings.Action("revisions.open_abandon"):
			return intents.OpenAbandon{}, true
		case keybindings.Action("revisions.open_details"):
			return intents.OpenDetails{}, true
		case keybindings.Action("revisions.open_duplicate"):
			return intents.OpenDuplicate{}, true
		case keybindings.Action("revisions.open_evolog"):
			return intents.OpenEvolog{}, true
		case keybindings.Action("revisions.open_inline_describe"):
			return intents.OpenInlineDescribe{}, true
		case keybindings.Action("revisions.open_rebase"):
			return intents.OpenRebase{}, true
		case keybindings.Action("revisions.open_revert"):
			return intents.OpenRevert{}, true
		case keybindings.Action("revisions.open_set_bookmark"):
			return intents.OpenSetBookmark{}, true
		case keybindings.Action("revisions.open_set_parents"):
			return intents.OpenSetParents{}, true
		case keybindings.Action("revisions.open_squash"):
			return intents.OpenSquash{}, true
		case keybindings.Action("revisions.page_down"):
			return intents.Navigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("revisions.page_up"):
			return intents.Navigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("revisions.quick_search_clear"):
			return intents.RevisionsQuickSearchClear{}, true
		case keybindings.Action("revisions.quick_search_next"):
			return intents.QuickSearchCycle{}, true
		case keybindings.Action("revisions.quick_search_prev"):
			return intents.QuickSearchCycle{Reverse: true}, true
		case keybindings.Action("revisions.refresh"):
			return intents.Refresh{}, true
		case keybindings.Action("revisions.split"):
			return intents.StartSplit{}, true
		case keybindings.Action("revisions.split_parallel"):
			return intents.StartSplit{IsParallel: true}, true
		case keybindings.Action("revisions.toggle_select"):
			return intents.RevisionsToggleSelect{}, true
		}
	case OwnerAbandon:
		switch action {
		case keybindings.Action("revisions.abandon.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.abandon.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.abandon.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.abandon.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.abandon.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.abandon.select_descendants"):
			return intents.AbandonSelectDescendants{}, true
		case keybindings.Action("revisions.abandon.toggle_select"):
			return intents.AbandonToggleSelect{}, true
		}
	case OwnerAceJump:
		switch action {
		case keybindings.Action("revisions.ace_jump.apply"):
			return intents.Apply{}, true
		case keybindings.Action("revisions.ace_jump.cancel"):
			return intents.Cancel{}, true
		}
	case OwnerDetails:
		switch action {
		case keybindings.Action("revisions.details.absorb"):
			return intents.DetailsAbsorb{}, true
		case keybindings.Action("revisions.details.cancel"):
			return intents.DetailsClose{}, true
		case keybindings.Action("revisions.details.diff"):
			return intents.DetailsDiff{}, true
		case keybindings.Action("revisions.details.move_down"):
			return intents.DetailsNavigate{Delta: 1}, true
		case keybindings.Action("revisions.details.move_up"):
			return intents.DetailsNavigate{Delta: -1}, true
		case keybindings.Action("revisions.details.page_down"):
			return intents.DetailsNavigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("revisions.details.page_up"):
			return intents.DetailsNavigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("revisions.details.quit"):
			return intents.Quit{}, true
		case keybindings.Action("revisions.details.refresh"):
			return intents.Refresh{}, true
		case keybindings.Action("revisions.details.restore"):
			return intents.DetailsRestore{}, true
		case keybindings.Action("revisions.details.revisions_changing_file"):
			return intents.DetailsRevisionsChangingFile{}, true
		case keybindings.Action("revisions.details.select_file"):
			return intents.DetailsSelectFile{File: actionargs.StringArg(args, "file", "")}, true
		case keybindings.Action("revisions.details.split"):
			return intents.DetailsSplit{}, true
		case keybindings.Action("revisions.details.split_parallel"):
			return intents.DetailsSplit{IsParallel: true}, true
		case keybindings.Action("revisions.details.squash"):
			return intents.DetailsSquash{}, true
		case keybindings.Action("revisions.details.toggle_select"):
			return intents.DetailsToggleSelect{}, true
		}
	case OwnerDetailsConfirmation:
		switch action {
		case keybindings.Action("revisions.details.confirmation.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.details.confirmation.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.details.confirmation.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.details.confirmation.next"):
			return intents.OptionSelect{Delta: 1}, true
		case keybindings.Action("revisions.details.confirmation.prev"):
			return intents.OptionSelect{Delta: -1}, true
		}
	case OwnerDuplicate:
		switch action {
		case keybindings.Action("revisions.duplicate.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.duplicate.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.duplicate.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.duplicate.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.duplicate.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.duplicate.set_target"):
			return intents.DuplicateSetTarget{Target: enumArgModeTarget(args, "target")}, true
		case keybindings.Action("revisions.duplicate.target_picker"):
			return intents.DuplicateOpenTargetPicker{}, true
		}
	case OwnerEvolog:
		switch action {
		case keybindings.Action("revisions.evolog.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.evolog.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.evolog.diff"):
			return intents.EvologDiff{}, true
		case keybindings.Action("revisions.evolog.move_down"):
			return intents.EvologNavigate{Delta: 1}, true
		case keybindings.Action("revisions.evolog.move_up"):
			return intents.EvologNavigate{Delta: -1}, true
		case keybindings.Action("revisions.evolog.page_down"):
			return intents.EvologNavigate{Delta: 1, IsPage: true}, true
		case keybindings.Action("revisions.evolog.page_up"):
			return intents.EvologNavigate{Delta: -1, IsPage: true}, true
		case keybindings.Action("revisions.evolog.quit"):
			return intents.Quit{}, true
		case keybindings.Action("revisions.evolog.restore"):
			return intents.EvologRestore{}, true
		}
	case OwnerInlineDescribe:
		switch action {
		case keybindings.Action("revisions.inline_describe.accept"):
			return intents.InlineDescribeAccept{}, true
		case keybindings.Action("revisions.inline_describe.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.inline_describe.editor"):
			return intents.InlineDescribeEditor{}, true
		}
	case OwnerQuickSearchInput:
		switch action {
		case keybindings.Action("revisions.quick_search.input.apply"):
			return intents.Apply{}, true
		case keybindings.Action("revisions.quick_search.input.cancel"):
			return intents.Cancel{}, true
		}
	case OwnerRebase:
		switch action {
		case keybindings.Action("revisions.rebase.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.rebase.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.rebase.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.rebase.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.rebase.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.rebase.set_source"):
			return intents.RebaseSetSource{Source: enumArgRebaseSource(args, "source")}, true
		case keybindings.Action("revisions.rebase.set_target"):
			return intents.RebaseSetTarget{Target: enumArgModeTarget(args, "target")}, true
		case keybindings.Action("revisions.rebase.skip_emptied"):
			return intents.RebaseToggleSkipEmptied{}, true
		case keybindings.Action("revisions.rebase.target_picker"):
			return intents.RebaseOpenTargetPicker{}, true
		}
	case OwnerRevert:
		switch action {
		case keybindings.Action("revisions.revert.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.revert.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.revert.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.revert.set_target"):
			return intents.RevertSetTarget{Target: enumArgModeTarget(args, "target")}, true
		case keybindings.Action("revisions.revert.target_picker"):
			return intents.RevertOpenTargetPicker{}, true
		}
	case OwnerSetBookmark:
		switch action {
		case keybindings.Action("revisions.set_bookmark.apply"):
			return intents.Apply{}, true
		case keybindings.Action("revisions.set_bookmark.autocomplete"):
			return intents.AutocompleteCycle{}, true
		case keybindings.Action("revisions.set_bookmark.autocomplete_back"):
			return intents.AutocompleteCycle{Reverse: true}, true
		case keybindings.Action("revisions.set_bookmark.cancel"):
			return intents.Cancel{}, true
		}
	case OwnerSetParents:
		switch action {
		case keybindings.Action("revisions.set_parents.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.set_parents.apply"):
			return intents.Apply{}, true
		case keybindings.Action("revisions.set_parents.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.set_parents.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.set_parents.toggle_select"):
			return intents.SetParentsToggleSelect{}, true
		}
	case OwnerSquash:
		switch action {
		case keybindings.Action("revisions.squash.ace_jump"):
			return intents.StartAceJump{}, true
		case keybindings.Action("revisions.squash.apply"):
			return intents.Apply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.squash.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revisions.squash.force_apply"):
			return intents.Apply{Force: true}, true
		case keybindings.Action("revisions.squash.interactive"):
			return intents.SquashToggleOption{Option: intents.SquashOptionInteractive}, true
		case keybindings.Action("revisions.squash.jump_to_working_copy"):
			return intents.Navigate{Target: intents.TargetWorkingCopy}, true
		case keybindings.Action("revisions.squash.keep_emptied"):
			return intents.SquashToggleOption{Option: intents.SquashOptionKeepEmptied}, true
		case keybindings.Action("revisions.squash.target_picker"):
			return intents.SquashOpenTargetPicker{}, true
		case keybindings.Action("revisions.squash.use_destination_msg"):
			return intents.SquashToggleOption{Option: intents.SquashOptionUseDestinationMessage}, true
		}
	case OwnerTargetPicker:
		switch action {
		case keybindings.Action("revisions.target_picker.apply"):
			return intents.TargetPickerApply{Force: actionargs.BoolArg(args, "force", false)}, true
		case keybindings.Action("revisions.target_picker.autocomplete"):
			return intents.AutocompleteCycle{}, true
		case keybindings.Action("revisions.target_picker.autocomplete_back"):
			return intents.AutocompleteCycle{Reverse: true}, true
		case keybindings.Action("revisions.target_picker.cancel"):
			return intents.TargetPickerCancel{}, true
		case keybindings.Action("revisions.target_picker.force_apply"):
			return intents.TargetPickerApply{Force: true}, true
		case keybindings.Action("revisions.target_picker.move_down"):
			return intents.TargetPickerNavigate{Delta: 1}, true
		case keybindings.Action("revisions.target_picker.move_up"):
			return intents.TargetPickerNavigate{Delta: -1}, true
		}
	case OwnerRevset:
		switch action {
		case keybindings.Action("revset.apply"):
			return intents.Apply{}, true
		case keybindings.Action("revset.autocomplete"):
			return intents.CompletionCycle{}, true
		case keybindings.Action("revset.autocomplete_back"):
			return intents.CompletionCycle{Reverse: true}, true
		case keybindings.Action("revset.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("revset.edit"):
			return intents.Edit{Clear: actionargs.BoolArg(args, "clear", false)}, true
		case keybindings.Action("revset.move_down"):
			return intents.CompletionMove{Delta: 1}, true
		case keybindings.Action("revset.move_up"):
			return intents.CompletionMove{Delta: -1}, true
		case keybindings.Action("revset.reset"):
			return intents.Reset{}, true
		case keybindings.Action("revset.set"):
			return intents.Set{Value: actionargs.StringArg(args, "value", "")}, true
		}
	case OwnerStatusInput:
		switch action {
		case keybindings.Action("status.input.apply"):
			return intents.Apply{}, true
		case keybindings.Action("status.input.autocomplete"):
			return intents.SuggestCycle{}, true
		case keybindings.Action("status.input.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("status.input.move_down"):
			return intents.SuggestNavigate{Delta: -1}, true
		case keybindings.Action("status.input.move_up"):
			return intents.SuggestNavigate{Delta: 1}, true
		case keybindings.Action("status.input.page_down"):
			return intents.SuggestNavigate{Delta: -1}, true
		case keybindings.Action("status.input.page_up"):
			return intents.SuggestNavigate{Delta: 1}, true
		}
	case OwnerUi:
		switch action {
		case keybindings.Action("ui.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("ui.exec_jj"):
			return intents.ExecJJ{}, true
		case keybindings.Action("ui.exec_shell"):
			return intents.ExecShell{}, true
		case keybindings.Action("ui.expand_status"):
			return intents.ExpandStatusToggle{}, true
		case keybindings.Action("ui.file_search_toggle"):
			return intents.FileSearchToggle{}, true
		case keybindings.Action("ui.open_bookmarks"):
			return intents.OpenBookmarks{}, true
		case keybindings.Action("ui.open_command_history"):
			return intents.CommandHistoryToggle{}, true
		case keybindings.Action("ui.open_git"):
			return intents.OpenGit{}, true
		case keybindings.Action("ui.open_help"):
			return intents.OpenHelp{}, true
		case keybindings.Action("ui.open_oplog"):
			return intents.OpLogOpen{}, true
		case keybindings.Action("ui.open_redo"):
			return intents.Redo{}, true
		case keybindings.Action("ui.open_revset"):
			return intents.Edit{Clear: true}, true
		case keybindings.Action("ui.open_undo"):
			return intents.Undo{}, true
		case keybindings.Action("ui.preview_expand"):
			return intents.PreviewExpand{}, true
		case keybindings.Action("ui.preview_half_page_down"):
			return intents.PreviewScroll{Kind: intents.PreviewHalfPageDown}, true
		case keybindings.Action("ui.preview_half_page_up"):
			return intents.PreviewScroll{Kind: intents.PreviewHalfPageUp}, true
		case keybindings.Action("ui.preview_scroll_down"):
			return intents.PreviewScroll{Kind: intents.PreviewScrollDown}, true
		case keybindings.Action("ui.preview_scroll_up"):
			return intents.PreviewScroll{Kind: intents.PreviewScrollUp}, true
		case keybindings.Action("ui.preview_shrink"):
			return intents.PreviewShrink{}, true
		case keybindings.Action("ui.preview_toggle"):
			return intents.PreviewToggle{}, true
		case keybindings.Action("ui.preview_toggle_bottom"):
			return intents.PreviewToggleBottom{}, true
		case keybindings.Action("ui.quick_search"):
			return intents.QuickSearch{}, true
		case keybindings.Action("ui.quit"):
			return intents.Quit{}, true
		case keybindings.Action("ui.suspend"):
			return intents.Suspend{}, true
		}
	case OwnerUiPreview:
		switch action {
		case keybindings.Action("ui.preview.show"):
			return intents.PreviewShow{Content: actionargs.StringArg(args, "content", "")}, true
		}
	case OwnerUndo:
		switch action {
		case keybindings.Action("undo.apply"):
			return intents.Apply{}, true
		case keybindings.Action("undo.cancel"):
			return intents.Cancel{}, true
		case keybindings.Action("undo.next"):
			return intents.OptionSelect{Delta: 1}, true
		case keybindings.Action("undo.prev"):
			return intents.OptionSelect{Delta: -1}, true
		}
	}
	return nil, false
}

func enumArgModeTarget(args map[string]any, name string) intents.ModeTarget {
	var zero intents.ModeTarget
	if args == nil {
		return zero
	}
	v, ok := args[name]
	if !ok {
		return zero
	}
	s, ok := v.(string)
	if !ok {
		return zero
	}
	switch s {
	case "onto":
		return intents.ModeTargetDestination
	case "after":
		return intents.ModeTargetAfter
	case "before":
		return intents.ModeTargetBefore
	case "insert":
		return intents.ModeTargetInsert
	default:
		return zero
	}
}

func enumArgRebaseSource(args map[string]any, name string) intents.RebaseSource {
	var zero intents.RebaseSource
	if args == nil {
		return zero
	}
	v, ok := args[name]
	if !ok {
		return zero
	}
	s, ok := v.(string)
	if !ok {
		return zero
	}
	switch s {
	case "revision":
		return intents.RebaseSourceRevision
	case "branch":
		return intents.RebaseSourceBranch
	case "source":
		return intents.RebaseSourceDescendants
	default:
		return zero
	}
}
